#
#  build-and-test.yml - GitHub Actions CI for swmm-solver
#
#  Created: May 19, 2019
#  Updated: May 31, 2019
#
#  Author: Michael E. Tryby
#          US EPA - ORD/CESER
#

name: Build and Test

on:
  push:
    branches: [ upstream-dev ]
  pull_request:
    branches: [ upstream-dev ]

jobs:
  win_build:
    runs-on: windows-2016
    defaults:
      run:
        shell: cmd
    env:
      PROJECT: swmm
      BUILD_HOME: build
      TEST_HOME: nrtests

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r tools/requirements-win.txt

    - name: Build and unit test
      run: tools/make.cmd /t

    - name: Build for reg test
      run: tools/make.cmd

    - name: Before reg test
      run: tools/before-nrtest.cmd

    - name: Run reg test
      run: tools/run-nrtests.cmd %GITHUB_SHA% %GITHUB_RUN_ID%_%GITHUB_RUN_NUMBER%

    - name: Upload artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: nrtest-artifacts
        path: upload/
